### ISSUE TITLE
torch.index_select() => IndexError: index 447 is out of bounds for dimension 2 with size 447

### ISSUE THREAD

**Issue by guynich** [nyrahealth/CrisperWhisper#20]
Many thanks for sharing the `nyrahealth/CrisperWhisper` model!  

I'm interested by its potential for verbatim transcriptions and to have reduced hallucinations.

I adapted the model card code `pipeline()` example to infer test datasets from the [HuggingFace OpenASR leaderboard](https://huggingface.co/spaces/hf-audio/open_asr_leaderboard) such as AMI and Gigaspeech. In [my code](https://gist.github.com/guynich/d4aba56aa7bd0e07c6bf4d4ece06c54b) I’m hitting the following error with AMI dataset after six hours of running on an A10 GPU.
```
Map:  76%|██████████████████████████████████████████████████▊                | 9579/12643 [6:10:38<1:25:12,  1.67s/ examplMap:  76%|███████████████████████████
███████████████████████▊                | 9579/12643 [6:10:56<1:58:39,  2.32s/ examples]                                     
Traceback (most recent call last):                                                                                           
  File "/home/ubuntu/hallucination_test_data/scripts/main3.py", line 84, in <module>                                         
    dataset.map(transcribe_batch, batched=True, batch_size=1)                                                                
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 560, in wrapper        
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                                                       
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3073, in map           
    for rank, done, content in Dataset._map_single(**dataset_kwargs):                                                        
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3476, in _map_single   
    batch = apply_function_on_filtered_inputs(                                                                               
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3338, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)                                                     
  File "/home/ubuntu/hallucination_test_data/scripts/main3.py", line 77, in transcribe_batch                                 
    transcriptions = pipe(audio_arrays, batch_size=len(audio_arrays))                                                        
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 283, in __call__
    return super().__call__(inputs, **kwargs)                                  
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1282, in __call__                                   
    outputs = list(final_iterator)                                                                                           
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)                                                                                               
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 269, in __next__
    processed = self.infer(next(self.iterator), **self.params)                                                                                                 
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1208, in forward  
    model_outputs = self._forward(model_inputs, **forward_params)                                                                                              
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 515, in _forward
    tokens = self.model.generate(                                                                                            
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 690, in generate
    ) = self.generate_with_fallback(                                                                                         
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 869, in generate_with_fallback
    seek_sequences, seek_outputs = self._postprocess_outputs(                                                                                                  
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 970, in _postprocess_outputs
    seek_outputs["token_timestamps"] = self._extract_token_timestamps(                                                                                         
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 221, in _extract_token_timestamps
    [                                  
  File "/home/ubuntu/venv_hallucination/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 222, in <listcomp>
    torch.index_select(weights[:, :, i, :], dim=0, index=beam_indices[:, i])                                                                                   
IndexError: index 447 is out of bounds for dimension 2 with size 447         
```
The same IndexError message for AMI dataset is also seen when running the code for the Gigaspeech dataset, but not with the other OpenASR leaderboard test datasets (e.g.: no error with spgispeech, Librispeech, TedLium, Voxpopuli).

Any suggestions for what might be going wrong?

**Comment by LaurinmyReha** [comment]
could you try installing this fork of transformers and check if this resolves your issue:

pip install git+https://github.com/nyrahealth/transformers.git@crisper_whisper

**Comment by guynich** [comment]
Thank you for the fast answer.  I'll check this and report back.

**Comment by guynich** [comment]
Great - the issue is fixed with AMI test dataset.  I'm running Gigaspeech test dataset now.  Closing this issue.  Many thanks [LaurinmyReha](https://github.com/LaurinmyReha)!

nit: during my check I did run into a `tokenizers` version conflict and worked around that.
```
The conflict is caused by:
    useful-moonshine-onnx 20241016 depends on tokenizers>=0.19.0
    transformers 4.37.2 depends on tokenizers<0.19 and >=0.14
 ```
